### PR TITLE
Fix references to prefix_wasm_api

### LINKED ISSUE #418: build failture with wasmtime
```
vscode@docker-desktop:~/proxy-wasm-cpp-host$ bazel build --define=engine=multi :lib
INFO: Analyzed target //:lib (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /build/proxy-wasm-cpp-host/BUILD:246:11: Compiling src/wasmtime/prefixed_wasmtime.cc failed: (Exit 1): gcc failed: error executing command (from target //:prefixed_wasmtime_lib) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++14' -MD -MF ... (remaining 29 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from bazel-out/aarch64-fastbuild/bin/src/wasmtime/prefixed_wasmtime.cc:27:
bazel-out/aarch64-fastbuild/bin/src/wasmtime/prefixed_types.h:16:10: fatal error: crates/c-api/include/prefixed_wasm.h: No such file or directory
   16 | #include "crates/c-api/include/prefixed_wasm.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //:lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.030s, Critical Path: 7.29s
INFO: 454 processes: 10 internal, 1 local, 443 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

### PR DESCRIPTION
**Pull request by keithmattix**
References to `include/wasm.h` changed to `crates/c-api/include/wasm.h`, so the prefixed api output needs to change as well. Fixes #418

### CODE REVIEW

**Comment by keithmattix** [comment]
Fixes #418

**Comment by PiotrSikora** [comment]
@keithmattix The change looks fine, but could you please confirm that it fixes the build and tests with `--define=engine=multi`? The CI doesn't check that configuration due to time constraints. Thanks!

**Comment by krinkinmu** [comment]
@PiotrSikora FWIW, I faced the same problem as in #418 and arrived to the same fix as @keithmattix did. I checked that it addresses the problem for me and the command from #418 works for me now:

```
bazel build --define=engine=multi :lib
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed target //:lib (0 packages loaded, 71587 targets configured).
INFO: Found 1 target...
Target //:lib up-to-date (nothing to build)
INFO: Elapsed time: 3.186s, Critical Path: 0.70s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

**Review by PiotrSikora — APPROVED** [review]
LGTM, thanks!

**Comment by PiotrSikora** [comment]
@mpwarres @martijneken could you guys review and merge it? Thanks!

**Comment by PiotrSikora** [comment]
> @mpwarres @martijneken could you guys review and merge it? Thanks!

Ping?

**Comment by keithmattix** [comment]
@martijneken @mpwarres ping?

**Review by mpwarres — APPROVED** [review]

**Comment by mpwarres** [comment]
Sorry for the delay and thanks for the nudge, this fell through the cracks. Thanks for the fix!

**Pull request merged**
