### PR TITLE
v8: add missing <cstdint> includes.

### PR DESCRIPTION
**Pull request by martijneken**
Copy changes from envoyproxy/envoy#29425.

This is a temporary build fix until #382 (major v8 upgrade, 10.7 -> 12.0).

### CODE REVIEW

**Comment by PiotrSikora** [comment]
LGTM. Note that we usually concatenate all patches to `v8.patch`, so that it's easier to propagate the same file to Envoy.

**Comment by PiotrSikora** [comment]
> LGTM. Note that we usually concatenate all patches to `v8.patch`, so that it's easier to propagate the same file to Envoy.

Ah, nevermind. I see it came from Envoy.

**Review by PiotrSikora — APPROVED** [review]

**Comment by martijneken** [comment]
Looks like I can't merge it, please do the honors.
"The base branch restricts merging to authorized users"

**Comment by PiotrSikora** [comment]
> Looks like I can't merge it, please do the honors. "The base branch restricts merging to authorized users"

I don't have admin anymore, so I cannot override the other failing tests (macOS and cargo-raze). cc @mpwarres

**Pull request merged**
