### PR TITLE
Fix segfault when failing to instantiate Wasm module.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Review by mathetake — COMMENTED** [review]
do you want to add tests (as I see we have tests for all runtime)?

**Review by mathetake — APPROVED** [review]

**Comment by PiotrSikora** [comment]
@mathetake in my attempt to fix WAVM on the CI, I've added checks for all (?) failures in `load()`, `link()` and `clone()`, other than those in stlib allocations. We originally skipped them, since they go against Envoy's coding style, but I think it makes sense to have them now. PTAL.

Unfortunately, this didn't fix the test with WAVM on the CI. I suspect that it fails because of a failure in `emplace` running out of memory or something like that, but since it passes locally, and it's not the primary runtime, I'm going to skip it for now.

**Comment by PiotrSikora** [comment]
> @mathetake in my attempt to fix WAVM on the CI, I've added checks for all (?) failures in `load()`, `link()` and `clone()`, other than those in stlib allocations. We originally skipped them, since they go against Envoy's coding style, but I think it makes sense to have them now. PTAL.

Done. Good call, thanks!

**Review by mathetake — APPROVED** [review]
👍

**Pull request merged**
