### PR TITLE
wasmtime: update to v0.31.0.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Envoy PR: https://github.com/envoyproxy/envoy/pull/18860

**Comment by PiotrSikora** [comment]
Bazel Query (in Envoy PR) complains about duplicated dependency on `libc` in `errno` crate, but they are in separate `selects.with_or` statements, so it's a false positive. Those build rules are auto-generated by `cargo-raze` and correct, so I'm not sure what's the best fix here... Maybe manual concatenation of `selects.with_or` statements?

**Comment by PiotrSikora** [comment]
`cargo-raze` issue tracked here: https://github.com/google/cargo-raze/issues/451, but let's get this in with manual fixes in the meantime.

**Review by mathetake — APPROVED** [review]
Ack 👍

**Pull request merged**
