### PR TITLE
Cluster specific gRPC call and establish stream

### PR DESCRIPTION
**Pull request by Shikugawa**
Related with https://github.com/envoyproxy/envoy-wasm/issues/594.

Bump ABI version to 0.2.2 and support to create gRPC call and establish stream by specifying cluster name directly as first argument, not GrpcService API. 

cc @PiotrSikora

### CODE REVIEW

**Review by PiotrSikora — CHANGES_REQUESTED** [review]
I actually didn't mean that you should add new functions to the ABI, only that you should bump patch-version to indicate that `grpcCall` and `grpcStream` can accept cluster name as the first parameter. Sorry for the confusion.

**Comment by Shikugawa** [comment]
@PiotrSikora Deleted new function and add some comments to `grpcCall` and `grpcStream`.

**Review by mathetake — APPROVED** [review]
LGTM, though I'm just curious if this can be just included in v1.0.0 ABI @PiotrSikora is working on, rather than bumping up to 0.2.2.

**Comment by Shikugawa** [comment]
@mathetake IMO, bumping up to 0.2.2 with this patch is better choice than waiting for 1.0.0, only to consider including Envoy 1.18.

**Comment by PiotrSikora** [comment]
> LGTM, though I'm just curious if this can be just included in v1.0.0 ABI @PiotrSikora is working on, rather than bumping up to 0.2.2.

This is already included in next version of the ABI, but the question is whether we could ship it now (as ABI v0.2.2), since there is no guarantee that we can get the next version of the ABI merged before the next Envoy release in ~4 weeks.

The need to bump ABI to v0.2.2 is questionable (even though I suggested it), since the ABI doesn't really change, and we're using it as a way to signal the new format acceptable as the first parameter, but in theory, we could rely on proxy returning `BadArgument` / `ParseFailure` in case it doesn't (which is what's happening now), without the need to bump the ABI.

Any thoughts?

**Comment by Shikugawa** [comment]
> The need to bump ABI to v0.2.2 is questionable (even though I suggested it), since the ABI doesn't really change, and we're using it as a way to signal the new format acceptable as the first parameter, but in theory, we could rely on proxy returning `BadArgument` / `ParseFailure` in case it doesn't (which is what's happening now), without the need to bump the ABI.

@PiotrSikora Yeah. I'd planned to fallback to try parse passed `service_name` as `cluster_name` on my first consideration. It will accept not only old style GrpcService but cluster name described at https://github.com/envoyproxy/envoy/issues/15170, so that we don't have to change ABI, I thought, because it was Envoy level behavior change, not ABI. But, bumping up v0.2.2 is also making sense to avoid unexpected behavior. But I don't have any idea for enduser to face unexpected break with updating Envoy to 1.18.0 with keeping ABI version 0.2.1.

**Comment by mathetake** [comment]
I would prefer not to bumping up this time since 1) this is kind of Envoy specific behavior change as we agree, and 2) there's already too much confusion around ABI versions due to lack of documentation.

**Comment by PiotrSikora** [comment]
> I would prefer not to bumping up this time since 1) this is kind of Envoy specific behavior change as we agree, and 2) there's already too much confusion around ABI versions due to lack of documentation.

Agreed (see: https://github.com/envoyproxy/envoy/pull/15208#pullrequestreview-603872549).

**Pull request closed without merging**
