### PR TITLE
Fix the doc comment for WasmVm::runtime.

### PR DESCRIPTION
**Pull request by jpeach**

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@jpeach any update on the CLA?

**Comment by jpeach** [comment]
> @jpeach any update on the CLA?

Just confirming some of the info, thanks for checking :)

**Comment by mathetake** [comment]
ping @jpeach on CLA?

**Comment by jpeach** [comment]
I'll try to deal with the CLA again if I have a more substantial change :)

**Pull request closed without merging**
